### PR TITLE
feat(lib): impl Clone for SpannedIter

### PR DESCRIPTION
**Pull request by moenie99**
I haven't done this before, I hope it is correct

### CODE REVIEW

**Comment by jeertmans** [comment]
Hello! Thanks for your PR!

Could you use the Derive macro instead?

Please make sure to pass rustfmt and clippy :)

**Comment by moenie99** [comment]
deriving clone doesn't generate the Token::Extras: Clone bound that is necessary to get a Clone instance for Lexer

**Comment by jeertmans** [comment]
How yes my bad, just noticed Lexer’s clone was implemented the same way :)

Can you then fix Rustfmt?

**Comment by moenie99** [comment]
i tried to figure it out but im not sure if i did it correctly as i never did this before, sorry. i did run rustfmt though

**Comment by jeertmans** [comment]
Look’s perfect! Thanks :)

**Pull request merged**
