### PR TITLE
chore(ci): automatically build handbook

### PR DESCRIPTION
**Pull request by jeertmans**
Hello, this small PR to propose automating the build and deploying of Logos handbook.

This will surely help people see new versions of the handbook. Currently, this deploys from the book branch, but in the end it should use the master branch.

This PR also rebases onto the master branch.

A small setup is required from your site to allow deploying a GitHub page from a workflow from the book branch.

### CODE REVIEW

**Comment by maciejhirsz** [comment]
> small PR

image

:sweat_smile: 

It's a bit hard to review, I'll try to rebase the `book` branch when I get a moment.

**Review by maciejhirsz — APPROVED** [review]

**Comment by maciejhirsz** [comment]
Diff got a bit wonky, but this works, cheers!

**Comment by jeertmans** [comment]
Nice! I will soon start to work a bit on the handbook. Do you prefer that I do PRs on your book branch or on the master one?

**Comment by maciejhirsz** [comment]
I'd say let's keep it in the `book` for now until content is a functional MVP.

**Pull request merged**
