### PR TITLE
[Debug] Test `s390x` environment

### PR DESCRIPTION
**Pull request by LecrisUT**
@jeertmans here is a debug workflow that would hopefully work. I'm not deeply involved into rust so I hope you can help compensate for that

### CODE REVIEW

**Comment by LecrisUT** [comment]
Welp it ran, but it is failing on other stuff. Locally I seem to have more luck:
```dockerfile
FROM s390x/fedora:latest

RUN dnf install -y git cargo

RUN git clone https://github.com/maciejhirsz/logos /logos

WORKDIR /logos

CMD ["cargo", "test", "--workspace", "--verbose"]
```
You need to pass `--arch`/`--platform` flags though:
```console
$ podman build --arch s390x -f ./Containerfile -t debug:logos-s390x
$ podman run --arch s390x debug:logos-s390x
```

**Comment by LecrisUT** [comment]
Same issue when running `docker` recommendation, maybe it's a `docker` issue instead

**Comment by jeertmans** [comment]
There seem to be be many issues, probably unrelated to this crate, see for example:

error: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

**Comment by LecrisUT** [comment]
Yes, I reckon it's an issue with the GH action environment. Running it locally I am able circumvent these. I couldn't find a solution to run these in a GH Actions environment. I can setup such that it runs in `copr` on my fork if that's an acceptable alternative

**Comment by jeertmans** [comment]
> Yes, I reckon it's an issue with the GH action environment. Running it locally I am able circumvent these. I couldn't find a solution to run these in a GH Actions environment. I can setup such that it runs in `copr` (native s390x machines) on my fork if that's an acceptable alternative

Any alternative is fine as long as the error message / issue is the same (I mean, any bug is worth being reported), and that we can reproduce it.

**Comment by LecrisUT** [comment]
You can navigate the CI in my fork: https://github.com/LecrisUT/logos/tree/debug/s390x

Navigate to the copr build page ([example](https://copr.fedorainfracloud.org/coprs/lecris/logos-s390x/build/8131581/)) and in the log of `builder-live.log` search for the section `Executing(%check)`, that is where the `cargo test` is being run. Feel free to make any changes in the branch it should be picked up when it build in `copr`

**Comment by LecrisUT** [comment]
Ok, this variant finally successfully failed: [builder-live.log](https://download.copr.fedorainfracloud.org/results/lecris/logos-s390x/fedora-rawhide-s390x/08131581-logos/builder-live.log.gz)

**Comment by LecrisUT** [comment]
Resolved with #431

**Pull request closed without merging**
